name: extract-audio

on:
  workflow_dispatch:
    inputs:
      video_link:
        description: "video link to extract audio"
        required: true
        default: "https://www.bilibili.com/video/BV1KY411g7iA"
      final_music_name:
        description: "music name upload to cloud"
        required: false
        default: "use video name as music name"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          npm ci

      - name: extract video from target video
        run: |
          export "VIDEO_LINK=${{ github.event.inputs.video_link }}"
          export "FINAL_MUSIC_NAME=${{ github.event.inputs.final_music_name }}"
          python audio-extractor.py

      - name: Upload audio to NetEaseMusic
        run: |
          node index.js
        env:
          PHONE: ${{ secrets.PHONE }}
          PASSWORD: ${{ secrets.PASSWORD }}
