name: extract-audio

on:
  workflow_dispatch:
    inputs:
      video_link:
        description: "video link to extract audio"
        required: true
        default: "https://www.bilibili.com/video/BV1KY411g7iA"
      final_music_name:
        description: "input music name "
        required: true
        default: "镰仓殿的13人"

jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          npm ci

      - name: extract audio from target video
        run: |
          pwd
          ls -al
          you-get --debug --output-filename "${{ github.event.inputs.final_music_name }}" --no-caption ${{ github.event.inputs.video_link }}  
          export "VIDEO_LINK=${{ github.event.inputs.video_link }}"
          export "FINAL_MUSIC_NAME=${{ github.event.inputs.final_music_name }}"
          ls -a
          ./audio-extractor.py

      - name: Upload audio to NetEaseMusic
        run: |
          node index.js
        env:
          PHONE: ${{ secrets.PHONE }}
          PASSWORD: ${{ secrets.PASSWORD }}
