name: extract-audio

on:
  workflow_dispatch:
    inputs:
      video_link:
        description: "video link to extract audio"
        required: true
        default: "https://www.bilibili.com/video/BV1KY411g7iA"
      final_music_name:
        description: "input music name "
        required: true
        default: "镰仓殿的13人"

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          npm ci

      - name: extract video from target video
        run: |
          pwd
          ls -al
          you-get -O ${{ github.event.inputs.final_music_name }} --no-caption ${{ github.event.inputs.video_link }}  
          export "VIDEO_LINK=${{ github.event.inputs.video_link }}"
          export "FINAL_MUSIC_NAME=${{ github.event.inputs.final_music_name }}"
          ls -al
          python audio-extractor.py

      - name: Upload audio to NetEaseMusic
        run: |
          node index.js
        env:
          PHONE: ${{ secrets.PHONE }}
          PASSWORD: ${{ secrets.PASSWORD }}
